---
stages:
  data_pyro_sdis_testset:
    cmd:
      - >-
        uv run ./scripts/install_local_huggingface_dataset.py
        --save-dir "./data/raw/pyro-sdis-testset/"
        --data-dir "./data/raw/pyro-sdis-testset-parquet/"
        --loglevel "info"
    deps:
      - ./scripts/install_local_huggingface_dataset.py
      - ./data/raw/pyro-sdis-testset-parquet/
    outs:
      - ./data/raw/pyro-sdis-testset/

  predictions_wise_wolf_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/pyro-sdis/val/predictions/wise_wolf/
        --dir-images "./data/raw/pyro-sdis/images/val/"
        --filepath-weights ./data/external/models/wise_wolf/weights/yolov11s.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/external/models/wise_wolf/weights/yolov11s.pt
    outs:
      - ./data/interim/pyro-sdis/val/predictions/wise_wolf/

  predictions_legendary_field_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/pyro-sdis/val/predictions/legendary_field/
        --dir-images "./data/raw/pyro-sdis/images/val/"
        --filepath-weights ./data/external/models/legendary_field/weights/legendary-field-19.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/external/models/legendary_field/weights/legendary-field-19.pt
    outs:
      - ./data/interim/pyro-sdis/val/predictions/legendary_field/

  predictions_wise_wolf_FP_2024:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/FP_2024/predictions/wise_wolf/
        --dir-images ./data/raw/FP_2024/
        --filepath-weights ./data/external/models/wise_wolf/weights/yolov11s.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/FP_2024/
      - ./data/external/models/wise_wolf/weights/yolov11s.pt
    outs:
      - ./data/interim/FP_2024/predictions/wise_wolf/

  crops_wise_wolf_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/crop_with_prediction.py
        --save-dir ./data/interim/pyro-sdis/val/crops/wise_wolf/
        --target-size 224
        --dir-images ./data/raw/pyro-sdis/images/val/
        --dir-predictions ./data/interim/pyro-sdis/val/predictions/wise_wolf
        --loglevel "info"
    deps:
      - ./scripts/crop_with_prediction.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/interim/pyro-sdis/val/predictions/wise_wolf
    outs:
      - ./data/interim/pyro-sdis/val/crops/wise_wolf/

  crops_wise_wolf_FP_2024:
    cmd:
      - >-
        uv run ./scripts/crop_with_prediction.py
        --save-dir ./data/interim/FP_2024/crops/wise_wolf/
        --target-size 224
        --dir-images ./data/raw/FP_2024/
        --dir-predictions ./data/interim/FP_2024/predictions/wise_wolf
        --loglevel "info"
    deps:
      - ./scripts/crop_with_prediction.py
      - ./data/raw/FP_2024/
      - ./data/interim/FP_2024/predictions/wise_wolf
    outs:
      - ./data/interim/FP_2024/crops/wise_wolf/

  filter_data_pyrosdis_smoke:
    cmd:
      - >-
        uv run ./scripts/filter_data_pyrosdis_smoke.py
        --save-dir ./data/interim/filtered/smoke/pyro-sdis/
        --dir-dataset ./data/raw/pyro-sdis/
        --loglevel "info"
    deps:
      - ./scripts/filter_data_pyrosdis_smoke.py
      - ./data/raw/pyro-sdis/
    outs:
      - ./data/interim/filtered/smoke/pyro-sdis/

  filter_data_figlib_smoke:
    cmd:
      - >-
        uv run ./scripts/filter_data_figlib_smoke.py
        --save-dir ./data/interim/filtered/smoke/FIGLIB_ANNOTATED_RESIZED/
        --dir-dataset ./data/raw/FIGLIB_ANNOTATED_RESIZED/
        --loglevel "info"
    deps:
      - ./scripts/filter_data_figlib_smoke.py
      - ./data/raw/FIGLIB_ANNOTATED_RESIZED/
    outs:
      - ./data/interim/filtered/smoke/FIGLIB_ANNOTATED_RESIZED/

  filter_data_pyronear_ds_smoke:
    cmd:
      - >-
        uv run ./scripts/filter_data_pyronear_ds_smoke.py
        --save-dir ./data/interim/filtered/smoke/pyronear_ds_03_2024/
        --allowed-dataset-prefixes "pyronear" "awf" "random" "adf"
        --dir-dataset ./data/raw/pyronear_ds_03_2024/
        --loglevel "info"
    deps:
      - ./scripts/filter_data_pyronear_ds_smoke.py
      - ./data/raw/pyronear_ds_03_2024/
    outs:
      - ./data/interim/filtered/smoke/pyronear_ds_03_2024/

  split_data_figlib:
    cmd:
      - >-
        uv run ./scripts/split_figlib.py
        --save-dir ./data/interim/data-split/smoke/FIGLIB_ANNOTATED_RESIZED/
        --dir-dataset ./data/interim/filtered/smoke/FIGLIB_ANNOTATED_RESIZED/
        --random-seed 0
        --ratio-train-val 0.9
        --loglevel "info"
    deps:
      - ./scripts/split_figlib.py
      - ./data/interim/filtered/smoke/FIGLIB_ANNOTATED_RESIZED/
    outs:
      - ./data/interim/data-split/smoke/FIGLIB_ANNOTATED_RESIZED/

  merge_smoke_datasets:
    cmd:
      - >-
        uv run ./scripts/merge_smoke_datasets.py
        --save-dir ./data/interim/data-split/smoke/wildfire/
        --dir-datasets ./data/interim/data-split/smoke/FIGLIB_ANNOTATED_RESIZED/ ./data/interim/filtered/smoke/pyro-sdis/ ./data/interim/filtered/smoke/pyronear_ds_03_2024/
        --loglevel "info"
    deps:
      - ./scripts/merge_smoke_datasets.py
      - ./data/interim/data-split/smoke/FIGLIB_ANNOTATED_RESIZED/
      - ./data/interim/filtered/smoke/pyro-sdis/
      - ./data/interim/filtered/smoke/pyronear_ds_03_2024/
    outs:
      - ./data/interim/data-split/smoke/wildfire/
