---
stages:
  data_pyro_sdis_testset:
    cmd:
      - >-
        uv run ./scripts/install_local_huggingface_dataset.py
        --save-dir "./data/raw/pyro-sdis-testset/"
        --data-dir "./data/raw/pyro-sdis-testset-parquet/"
        --loglevel "info"
    deps:
      - ./scripts/install_local_huggingface_dataset.py
      - ./data/raw/pyro-sdis-testset-parquet/
    outs:
      - ./data/raw/pyro-sdis-testset/

  predictions_wise_wolf_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/pyro-sdis/val/predictions/wise_wolf/
        --dir-images "./data/raw/pyro-sdis/images/val/"
        --filepath-weights ./data/external/models/wise_wolf/weights/yolov11s.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/external/models/wise_wolf/weights/yolov11s.pt
    outs:
      - ./data/interim/pyro-sdis/val/predictions/wise_wolf/

  predictions_legendary_field_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/pyro-sdis/val/predictions/legendary_field/
        --dir-images "./data/raw/pyro-sdis/images/val/"
        --filepath-weights ./data/external/models/legendary_field/weights/legendary-field-19.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/external/models/legendary_field/weights/legendary-field-19.pt
    outs:
      - ./data/interim/pyro-sdis/val/predictions/legendary_field/

  predictions_wise_wolf_FP_2024:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/FP_2024/predictions/wise_wolf/
        --dir-images ./data/raw/FP_2024/
        --filepath-weights ./data/external/models/wise_wolf/weights/yolov11s.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/FP_2024/
      - ./data/external/models/wise_wolf/weights/yolov11s.pt
    outs:
      - ./data/interim/FP_2024/predictions/wise_wolf/

  crops_wise_wolf_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/crop_with_prediction.py
        --save-dir ./data/interim/pyro-sdis/val/crops/
        --target-size 224
        --dir-images ./data/raw/pyro-sdis/images/val/
        --dir-predictions ./data/interim/pyro-sdis/val/predictions/wise_wolf
        --loglevel "info"
    deps:
      - ./scripts/crop_with_prediction.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/interim/pyro-sdis/val/predictions/wise_wolf
    outs:
      - ./data/interim/pyro-sdis/val/crops/

  crops_wise_wolf_FP_2024:
    cmd:
      - >-
        uv run ./scripts/crop_with_prediction.py
        --save-dir ./data/interim/FP_2024/crops/
        --target-size 224
        --dir-images ./data/raw/FP_2024/
        --dir-predictions ./data/interim/FP_2024/predictions/wise_wolf
        --loglevel "info"
    deps:
      - ./scripts/crop_with_prediction.py
      - ./data/raw/FP_2024/
      - ./data/interim/FP_2024/predictions/wise_wolf
    outs:
      - ./data/interim/FP_2024/crops/
