---
stages:
  data_pyro_sdis_testset:
    cmd:
      - >-
        uv run ./scripts/install_local_huggingface_dataset.py
        --save-dir "./data/raw/pyro-sdis-testset/"
        --data-dir "./data/raw/pyro-sdis-testset-parquet/"
        --loglevel "info"
    deps:
      - ./scripts/install_local_huggingface_dataset.py
      - ./data/raw/pyro-sdis-testset-parquet/
    outs:
      - ./data/raw/pyro-sdis-testset/
  predictions_wise_wolf_pyro_sdis_val:
    cmd:
      - >-
        uv run ./scripts/predict.py
        --save-dir ./data/interim/pyro-sdis/val/predictions/wise_wolf/
        --dir-images "./data/raw/pyro-sdis/images/val/"
        --filepath-weights ./data/external/models/wise_wolf/weights/yolov11s.pt
        --loglevel "info"
    deps:
      - ./scripts/predict.py
      - ./data/raw/pyro-sdis/images/val/
      - ./data/external/models/wise_wolf/weights/yolov11s.pt
    outs:
      - ./data/interim/pyro-sdis/val/predictions/wise_wolf/
